### PR TITLE
visual improvements

### PR DESCRIPTION
**Pull request by ChristianGreiner**
I changed some css stuff so it looks like more than the original duality page.

- removed boxshadows, added simple border instead
- removed the unnecessary spin animation in categories
- adjusted colors
- fixed footer margin

### CODE REVIEW

**Comment by thomasburt255** [comment]
Nice, although I'd keep the spin animation, it looks visually appealing.

**Comment by ChristianGreiner** [comment]
@Kliktrix I added a simple transition effect instead 

image

**Comment by mfep** [comment]
Thank you! In my opinion, the header and footer definitely looks better, however I miss the background texture. Plain grey is just ... grey. I think we don't have to stick to the official page in this matter.

Is using bg textures very dated by today's standards?
If yes, can we re-iterate on the color a bit?

**Comment by ChristianGreiner** [comment]
1980's calling... they want their backgrounds back.
Just kidding 😋 So should I put back the background-texture? If no, what color do you prefer?

**Comment by mfep** [comment]
I tried different backgrounds, but had the impression, that they only fit with the original shadowy boxes. Also, coloring the background didn't help. Let's stick with your version for now.

**Pull request merged**
